about:
    home: 'http://www.bioinf.uni-leipzig.de/Software/segemehl/'
    license: free
    summary: Short read mapping with gaps

package:
  name: segemehl
  version: 0.2.0

source:
  fn: segemehl_0_2_0.tar.gz
  url: http://www.bioinf.uni-leipzig.de/Software/segemehl/segemehl_0_2_0.tar.gz
  sha256: 2575139d2f2ba7bd534afcbe485c0570c177d1faaeb267c4cd873e65b8e72afb

build:
  number: 0

requirements:
  build:
    - gcc   # [linux]
    - llvm  # [osx]
    - ncurses
  run:
    - libgcc    # [linux]

test:
  commands:
    - segemehl.x -h 2>&1 | grep VERSION | wc -l | awk '{if($1!=1){exit 1}}'